package com.icfcc.db.user;

import java.util.Date;

public class SmRole {
    private Integer intId;

    private String vcrRolecode;

    private String vcrName;

    private String vcrDesc;

    private Date tmsCreate;

    private Date tmsLastupdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_role.int_id
     *
     * @return the value of sm_role.int_id
     *
     * @mbggenerated
     */
    public Integer getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_role.int_id
     *
     * @param intId the value for sm_role.int_id
     *
     * @mbggenerated
     */
    public void setIntId(Integer intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_role.vcr_rolecode
     *
     * @return the value of sm_role.vcr_rolecode
     *
     * @mbggenerated
     */
    public String getVcrRolecode() {
        return vcrRolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_role.vcr_rolecode
     *
     * @param vcrRolecode the value for sm_role.vcr_rolecode
     *
     * @mbggenerated
     */
    public void setVcrRolecode(String vcrRolecode) {
        this.vcrRolecode = vcrRolecode == null ? null : vcrRolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_role.vcr_name
     *
     * @return the value of sm_role.vcr_name
     *
     * @mbggenerated
     */
    public String getVcrName() {
        return vcrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_role.vcr_name
     *
     * @param vcrName the value for sm_role.vcr_name
     *
     * @mbggenerated
     */
    public void setVcrName(String vcrName) {
        this.vcrName = vcrName == null ? null : vcrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_role.vcr_desc
     *
     * @return the value of sm_role.vcr_desc
     *
     * @mbggenerated
     */
    public String getVcrDesc() {
        return vcrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_role.vcr_desc
     *
     * @param vcrDesc the value for sm_role.vcr_desc
     *
     * @mbggenerated
     */
    public void setVcrDesc(String vcrDesc) {
        this.vcrDesc = vcrDesc == null ? null : vcrDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_role.tms_create
     *
     * @return the value of sm_role.tms_create
     *
     * @mbggenerated
     */
    public Date getTmsCreate() {
        return tmsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_role.tms_create
     *
     * @param tmsCreate the value for sm_role.tms_create
     *
     * @mbggenerated
     */
    public void setTmsCreate(Date tmsCreate) {
        this.tmsCreate = tmsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_role.tms_lastupdate
     *
     * @return the value of sm_role.tms_lastupdate
     *
     * @mbggenerated
     */
    public Date getTmsLastupdate() {
        return tmsLastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_role.tms_lastupdate
     *
     * @param tmsLastupdate the value for sm_role.tms_lastupdate
     *
     * @mbggenerated
     */
    public void setTmsLastupdate(Date tmsLastupdate) {
        this.tmsLastupdate = tmsLastupdate;
    }
}