package com.icfcc.db.user;

import org.apache.ibatis.annotations.Param;

public interface SmRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("intRoleid") Integer intRoleid, @Param("intMenuid") Integer intMenuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    int insert(SmRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    int insertSelective(SmRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    SmRoleMenu selectByPrimaryKey(@Param("intRoleid") Integer intRoleid, @Param("intMenuid") Integer intMenuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmRoleMenu record);
}