package com.icfcc.db.sys;

import com.icfcc.db.anon.MyBatisDao;

import java.util.List;

@MyBatisDao
public interface SmMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer iId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int insert(SmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int insertSelective(SmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    SmMenu selectByPrimaryKey(Integer iId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmMenu record);

    List<SmMenu> selectAll();
}