package com.icfcc.db.sys;


public interface SmMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int insert(SmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int insertSelective(SmMenu record);
}