package com.icfcc.db.user;

import java.util.Date;

public class SmUserAuth {
    private Integer intId;

    private Integer smIntId;

    private String vcrAuthcode;

    private String vcrAuthpwd;

    private String vcrEncrypttype;

    private Date tmsCreate;

    private Date tmsLastupdate;

    private Date tmsLastlogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.int_id
     *
     * @return the value of sm_user_auth.int_id
     *
     * @mbggenerated
     */
    public Integer getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.int_id
     *
     * @param intId the value for sm_user_auth.int_id
     *
     * @mbggenerated
     */
    public void setIntId(Integer intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.sm__int_id
     *
     * @return the value of sm_user_auth.sm__int_id
     *
     * @mbggenerated
     */
    public Integer getSmIntId() {
        return smIntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.sm__int_id
     *
     * @param smIntId the value for sm_user_auth.sm__int_id
     *
     * @mbggenerated
     */
    public void setSmIntId(Integer smIntId) {
        this.smIntId = smIntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.vcr_authcode
     *
     * @return the value of sm_user_auth.vcr_authcode
     *
     * @mbggenerated
     */
    public String getVcrAuthcode() {
        return vcrAuthcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.vcr_authcode
     *
     * @param vcrAuthcode the value for sm_user_auth.vcr_authcode
     *
     * @mbggenerated
     */
    public void setVcrAuthcode(String vcrAuthcode) {
        this.vcrAuthcode = vcrAuthcode == null ? null : vcrAuthcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.vcr_authpwd
     *
     * @return the value of sm_user_auth.vcr_authpwd
     *
     * @mbggenerated
     */
    public String getVcrAuthpwd() {
        return vcrAuthpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.vcr_authpwd
     *
     * @param vcrAuthpwd the value for sm_user_auth.vcr_authpwd
     *
     * @mbggenerated
     */
    public void setVcrAuthpwd(String vcrAuthpwd) {
        this.vcrAuthpwd = vcrAuthpwd == null ? null : vcrAuthpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.vcr_encrypttype
     *
     * @return the value of sm_user_auth.vcr_encrypttype
     *
     * @mbggenerated
     */
    public String getVcrEncrypttype() {
        return vcrEncrypttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.vcr_encrypttype
     *
     * @param vcrEncrypttype the value for sm_user_auth.vcr_encrypttype
     *
     * @mbggenerated
     */
    public void setVcrEncrypttype(String vcrEncrypttype) {
        this.vcrEncrypttype = vcrEncrypttype == null ? null : vcrEncrypttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.tms_create
     *
     * @return the value of sm_user_auth.tms_create
     *
     * @mbggenerated
     */
    public Date getTmsCreate() {
        return tmsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.tms_create
     *
     * @param tmsCreate the value for sm_user_auth.tms_create
     *
     * @mbggenerated
     */
    public void setTmsCreate(Date tmsCreate) {
        this.tmsCreate = tmsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.tms_lastupdate
     *
     * @return the value of sm_user_auth.tms_lastupdate
     *
     * @mbggenerated
     */
    public Date getTmsLastupdate() {
        return tmsLastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.tms_lastupdate
     *
     * @param tmsLastupdate the value for sm_user_auth.tms_lastupdate
     *
     * @mbggenerated
     */
    public void setTmsLastupdate(Date tmsLastupdate) {
        this.tmsLastupdate = tmsLastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.tms_lastlogin
     *
     * @return the value of sm_user_auth.tms_lastlogin
     *
     * @mbggenerated
     */
    public Date getTmsLastlogin() {
        return tmsLastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.tms_lastlogin
     *
     * @param tmsLastlogin the value for sm_user_auth.tms_lastlogin
     *
     * @mbggenerated
     */
    public void setTmsLastlogin(Date tmsLastlogin) {
        this.tmsLastlogin = tmsLastlogin;
    }
}