package com.icfcc.db.user;

import java.util.Date;

public class SmUserrole {
    private Integer intUserid;

    private Integer intRoleid;

    private Date tmsCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userrole.int_userid
     *
     * @return the value of sm_userrole.int_userid
     *
     * @mbggenerated
     */
    public Integer getIntUserid() {
        return intUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userrole.int_userid
     *
     * @param intUserid the value for sm_userrole.int_userid
     *
     * @mbggenerated
     */
    public void setIntUserid(Integer intUserid) {
        this.intUserid = intUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userrole.int_roleid
     *
     * @return the value of sm_userrole.int_roleid
     *
     * @mbggenerated
     */
    public Integer getIntRoleid() {
        return intRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userrole.int_roleid
     *
     * @param intRoleid the value for sm_userrole.int_roleid
     *
     * @mbggenerated
     */
    public void setIntRoleid(Integer intRoleid) {
        this.intRoleid = intRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userrole.tms_create
     *
     * @return the value of sm_userrole.tms_create
     *
     * @mbggenerated
     */
    public Date getTmsCreate() {
        return tmsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userrole.tms_create
     *
     * @param tmsCreate the value for sm_userrole.tms_create
     *
     * @mbggenerated
     */
    public void setTmsCreate(Date tmsCreate) {
        this.tmsCreate = tmsCreate;
    }
}