package com.icfcc.db.user;

import java.util.Date;

public class SmUserAuth {
    private Integer iId;

    private Integer iUserid;

    private String sAuthcode;

    private String sAuthpwd;

    private String sEncrypttype;

    private Date tsCreate;

    private Date tsLastupdate;

    private Date tsLastlogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.i_id
     *
     * @return the value of sm_user_auth.i_id
     *
     * @mbggenerated
     */
    public Integer getiId() {
        return iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.i_id
     *
     * @param iId the value for sm_user_auth.i_id
     *
     * @mbggenerated
     */
    public void setiId(Integer iId) {
        this.iId = iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.i_userid
     *
     * @return the value of sm_user_auth.i_userid
     *
     * @mbggenerated
     */
    public Integer getiUserid() {
        return iUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.i_userid
     *
     * @param iUserid the value for sm_user_auth.i_userid
     *
     * @mbggenerated
     */
    public void setiUserid(Integer iUserid) {
        this.iUserid = iUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.s_authcode
     *
     * @return the value of sm_user_auth.s_authcode
     *
     * @mbggenerated
     */
    public String getsAuthcode() {
        return sAuthcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.s_authcode
     *
     * @param sAuthcode the value for sm_user_auth.s_authcode
     *
     * @mbggenerated
     */
    public void setsAuthcode(String sAuthcode) {
        this.sAuthcode = sAuthcode == null ? null : sAuthcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.s_authpwd
     *
     * @return the value of sm_user_auth.s_authpwd
     *
     * @mbggenerated
     */
    public String getsAuthpwd() {
        return sAuthpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.s_authpwd
     *
     * @param sAuthpwd the value for sm_user_auth.s_authpwd
     *
     * @mbggenerated
     */
    public void setsAuthpwd(String sAuthpwd) {
        this.sAuthpwd = sAuthpwd == null ? null : sAuthpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.s_encrypttype
     *
     * @return the value of sm_user_auth.s_encrypttype
     *
     * @mbggenerated
     */
    public String getsEncrypttype() {
        return sEncrypttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.s_encrypttype
     *
     * @param sEncrypttype the value for sm_user_auth.s_encrypttype
     *
     * @mbggenerated
     */
    public void setsEncrypttype(String sEncrypttype) {
        this.sEncrypttype = sEncrypttype == null ? null : sEncrypttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.ts_create
     *
     * @return the value of sm_user_auth.ts_create
     *
     * @mbggenerated
     */
    public Date getTsCreate() {
        return tsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.ts_create
     *
     * @param tsCreate the value for sm_user_auth.ts_create
     *
     * @mbggenerated
     */
    public void setTsCreate(Date tsCreate) {
        this.tsCreate = tsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.ts_lastupdate
     *
     * @return the value of sm_user_auth.ts_lastupdate
     *
     * @mbggenerated
     */
    public Date getTsLastupdate() {
        return tsLastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.ts_lastupdate
     *
     * @param tsLastupdate the value for sm_user_auth.ts_lastupdate
     *
     * @mbggenerated
     */
    public void setTsLastupdate(Date tsLastupdate) {
        this.tsLastupdate = tsLastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_user_auth.ts_lastlogin
     *
     * @return the value of sm_user_auth.ts_lastlogin
     *
     * @mbggenerated
     */
    public Date getTsLastlogin() {
        return tsLastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_user_auth.ts_lastlogin
     *
     * @param tsLastlogin the value for sm_user_auth.ts_lastlogin
     *
     * @mbggenerated
     */
    public void setTsLastlogin(Date tsLastlogin) {
        this.tsLastlogin = tsLastlogin;
    }
}