package com.icfcc.db.user;

import java.util.Date;

public class SmUserbaseinfo {
    private Integer intId;

    private String name;

    private Date birthDay;

    private Integer deptId;

    private String gender;

    private Integer age;

    private String chrStatus;

    private Date tmsCreate;

    private Date tmsLastupdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.int_id
     *
     * @return the value of sm_userbaseinfo.int_id
     *
     * @mbggenerated
     */
    public Integer getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.int_id
     *
     * @param intId the value for sm_userbaseinfo.int_id
     *
     * @mbggenerated
     */
    public void setIntId(Integer intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.NAME
     *
     * @return the value of sm_userbaseinfo.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.NAME
     *
     * @param name the value for sm_userbaseinfo.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.BIRTH_DAY
     *
     * @return the value of sm_userbaseinfo.BIRTH_DAY
     *
     * @mbggenerated
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.BIRTH_DAY
     *
     * @param birthDay the value for sm_userbaseinfo.BIRTH_DAY
     *
     * @mbggenerated
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.DEPT_ID
     *
     * @return the value of sm_userbaseinfo.DEPT_ID
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.DEPT_ID
     *
     * @param deptId the value for sm_userbaseinfo.DEPT_ID
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.GENDER
     *
     * @return the value of sm_userbaseinfo.GENDER
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.GENDER
     *
     * @param gender the value for sm_userbaseinfo.GENDER
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.AGE
     *
     * @return the value of sm_userbaseinfo.AGE
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.AGE
     *
     * @param age the value for sm_userbaseinfo.AGE
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.chr_status
     *
     * @return the value of sm_userbaseinfo.chr_status
     *
     * @mbggenerated
     */
    public String getChrStatus() {
        return chrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.chr_status
     *
     * @param chrStatus the value for sm_userbaseinfo.chr_status
     *
     * @mbggenerated
     */
    public void setChrStatus(String chrStatus) {
        this.chrStatus = chrStatus == null ? null : chrStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.tms_create
     *
     * @return the value of sm_userbaseinfo.tms_create
     *
     * @mbggenerated
     */
    public Date getTmsCreate() {
        return tmsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.tms_create
     *
     * @param tmsCreate the value for sm_userbaseinfo.tms_create
     *
     * @mbggenerated
     */
    public void setTmsCreate(Date tmsCreate) {
        this.tmsCreate = tmsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.tms_lastupdate
     *
     * @return the value of sm_userbaseinfo.tms_lastupdate
     *
     * @mbggenerated
     */
    public Date getTmsLastupdate() {
        return tmsLastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.tms_lastupdate
     *
     * @param tmsLastupdate the value for sm_userbaseinfo.tms_lastupdate
     *
     * @mbggenerated
     */
    public void setTmsLastupdate(Date tmsLastupdate) {
        this.tmsLastupdate = tmsLastupdate;
    }
}