package com.icfcc.db.user;

import java.util.Date;

public class SmUserbaseinfo {
    private Integer iId;

    private String sName;

    private Date dBirthDay;

    private Integer iDeptId;

    private String sGender;

    private Integer iAge;

    private String sStatus;

    private Date tsCreate;

    private Date tsLastupdate;

    private SmUserAuth smUserAuth;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.i_id
     *
     * @return the value of sm_userbaseinfo.i_id
     *
     * @mbggenerated
     */
    public Integer getiId() {
        return iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.i_id
     *
     * @param iId the value for sm_userbaseinfo.i_id
     *
     * @mbggenerated
     */
    public void setiId(Integer iId) {
        this.iId = iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.s_NAME
     *
     * @return the value of sm_userbaseinfo.s_NAME
     *
     * @mbggenerated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.s_NAME
     *
     * @param sName the value for sm_userbaseinfo.s_NAME
     *
     * @mbggenerated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.D_BIRTH_DAY
     *
     * @return the value of sm_userbaseinfo.D_BIRTH_DAY
     *
     * @mbggenerated
     */
    public Date getdBirthDay() {
        return dBirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.D_BIRTH_DAY
     *
     * @param dBirthDay the value for sm_userbaseinfo.D_BIRTH_DAY
     *
     * @mbggenerated
     */
    public void setdBirthDay(Date dBirthDay) {
        this.dBirthDay = dBirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.i_DEPT_ID
     *
     * @return the value of sm_userbaseinfo.i_DEPT_ID
     *
     * @mbggenerated
     */
    public Integer getiDeptId() {
        return iDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.i_DEPT_ID
     *
     * @param iDeptId the value for sm_userbaseinfo.i_DEPT_ID
     *
     * @mbggenerated
     */
    public void setiDeptId(Integer iDeptId) {
        this.iDeptId = iDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.s_GENDER
     *
     * @return the value of sm_userbaseinfo.s_GENDER
     *
     * @mbggenerated
     */
    public String getsGender() {
        return sGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.s_GENDER
     *
     * @param sGender the value for sm_userbaseinfo.s_GENDER
     *
     * @mbggenerated
     */
    public void setsGender(String sGender) {
        this.sGender = sGender == null ? null : sGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.i_age
     *
     * @return the value of sm_userbaseinfo.i_age
     *
     * @mbggenerated
     */
    public Integer getiAge() {
        return iAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.i_age
     *
     * @param iAge the value for sm_userbaseinfo.i_age
     *
     * @mbggenerated
     */
    public void setiAge(Integer iAge) {
        this.iAge = iAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.s_status
     *
     * @return the value of sm_userbaseinfo.s_status
     *
     * @mbggenerated
     */
    public String getsStatus() {
        return sStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.s_status
     *
     * @param sStatus the value for sm_userbaseinfo.s_status
     *
     * @mbggenerated
     */
    public void setsStatus(String sStatus) {
        this.sStatus = sStatus == null ? null : sStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.ts_create
     *
     * @return the value of sm_userbaseinfo.ts_create
     *
     * @mbggenerated
     */
    public Date getTsCreate() {
        return tsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.ts_create
     *
     * @param tsCreate the value for sm_userbaseinfo.ts_create
     *
     * @mbggenerated
     */
    public void setTsCreate(Date tsCreate) {
        this.tsCreate = tsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_userbaseinfo.ts_lastupdate
     *
     * @return the value of sm_userbaseinfo.ts_lastupdate
     *
     * @mbggenerated
     */
    public Date getTsLastupdate() {
        return tsLastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_userbaseinfo.ts_lastupdate
     *
     * @param tsLastupdate the value for sm_userbaseinfo.ts_lastupdate
     *
     * @mbggenerated
     */
    public void setTsLastupdate(Date tsLastupdate) {
        this.tsLastupdate = tsLastupdate;
    }

    public SmUserAuth getSmUserAuth() {
        return smUserAuth;
    }

    public void setSmUserAuth(SmUserAuth smUserAuth) {
        this.smUserAuth = smUserAuth;
    }
}