package com.icfcc.db.user;


public interface SmUserbaseinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userbaseinfo
     *
     * @mbggenerated
     */
    int insert(SmUserbaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userbaseinfo
     *
     * @mbggenerated
     */
    int insertSelective(SmUserbaseinfo record);
}