package com.icfcc.db.user;


import com.icfcc.db.ano.MyBatisDao;

@MyBatisDao
public interface SmUserbaseinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userbaseinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer iId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userbaseinfo
     *
     * @mbggenerated
     */
    int insert(SmUserbaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userbaseinfo
     *
     * @mbggenerated
     */
    int insertSelective(SmUserbaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userbaseinfo
     *
     * @mbggenerated
     */
    SmUserbaseinfo selectByPrimaryKey(Integer iId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userbaseinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmUserbaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userbaseinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmUserbaseinfo record);
}