package com.icfcc.db.sys;

import java.util.Date;

public class SmMenu {
    private Integer intId;

    private String vcrName;

    private String vcrHref;

    private String vcrIcon;

    private String vcrTarget;

    private Integer intSort;

    private Boolean blnShow;

    private String vcrPermissioncode;

    private Date tmsCreate;

    private Date tmsLastupdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.int_id
     *
     * @return the value of sm_menu.int_id
     *
     * @mbggenerated
     */
    public Integer getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.int_id
     *
     * @param intId the value for sm_menu.int_id
     *
     * @mbggenerated
     */
    public void setIntId(Integer intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.vcr_name
     *
     * @return the value of sm_menu.vcr_name
     *
     * @mbggenerated
     */
    public String getVcrName() {
        return vcrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.vcr_name
     *
     * @param vcrName the value for sm_menu.vcr_name
     *
     * @mbggenerated
     */
    public void setVcrName(String vcrName) {
        this.vcrName = vcrName == null ? null : vcrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.vcr_href
     *
     * @return the value of sm_menu.vcr_href
     *
     * @mbggenerated
     */
    public String getVcrHref() {
        return vcrHref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.vcr_href
     *
     * @param vcrHref the value for sm_menu.vcr_href
     *
     * @mbggenerated
     */
    public void setVcrHref(String vcrHref) {
        this.vcrHref = vcrHref == null ? null : vcrHref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.vcr_icon
     *
     * @return the value of sm_menu.vcr_icon
     *
     * @mbggenerated
     */
    public String getVcrIcon() {
        return vcrIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.vcr_icon
     *
     * @param vcrIcon the value for sm_menu.vcr_icon
     *
     * @mbggenerated
     */
    public void setVcrIcon(String vcrIcon) {
        this.vcrIcon = vcrIcon == null ? null : vcrIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.vcr_target
     *
     * @return the value of sm_menu.vcr_target
     *
     * @mbggenerated
     */
    public String getVcrTarget() {
        return vcrTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.vcr_target
     *
     * @param vcrTarget the value for sm_menu.vcr_target
     *
     * @mbggenerated
     */
    public void setVcrTarget(String vcrTarget) {
        this.vcrTarget = vcrTarget == null ? null : vcrTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.int_sort
     *
     * @return the value of sm_menu.int_sort
     *
     * @mbggenerated
     */
    public Integer getIntSort() {
        return intSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.int_sort
     *
     * @param intSort the value for sm_menu.int_sort
     *
     * @mbggenerated
     */
    public void setIntSort(Integer intSort) {
        this.intSort = intSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.bln_show
     *
     * @return the value of sm_menu.bln_show
     *
     * @mbggenerated
     */
    public Boolean getBlnShow() {
        return blnShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.bln_show
     *
     * @param blnShow the value for sm_menu.bln_show
     *
     * @mbggenerated
     */
    public void setBlnShow(Boolean blnShow) {
        this.blnShow = blnShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.vcr_permissioncode
     *
     * @return the value of sm_menu.vcr_permissioncode
     *
     * @mbggenerated
     */
    public String getVcrPermissioncode() {
        return vcrPermissioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.vcr_permissioncode
     *
     * @param vcrPermissioncode the value for sm_menu.vcr_permissioncode
     *
     * @mbggenerated
     */
    public void setVcrPermissioncode(String vcrPermissioncode) {
        this.vcrPermissioncode = vcrPermissioncode == null ? null : vcrPermissioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.tms_create
     *
     * @return the value of sm_menu.tms_create
     *
     * @mbggenerated
     */
    public Date getTmsCreate() {
        return tmsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.tms_create
     *
     * @param tmsCreate the value for sm_menu.tms_create
     *
     * @mbggenerated
     */
    public void setTmsCreate(Date tmsCreate) {
        this.tmsCreate = tmsCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.tms_lastupdate
     *
     * @return the value of sm_menu.tms_lastupdate
     *
     * @mbggenerated
     */
    public Date getTmsLastupdate() {
        return tmsLastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.tms_lastupdate
     *
     * @param tmsLastupdate the value for sm_menu.tms_lastupdate
     *
     * @mbggenerated
     */
    public void setTmsLastupdate(Date tmsLastupdate) {
        this.tmsLastupdate = tmsLastupdate;
    }
}