package com.icfcc.db.user;


public interface SmRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int insert(SmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int insertSelective(SmRole record);
}