package com.icfcc.db.user;

import org.apache.ibatis.annotations.Param;

public interface SmUserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("intUserid") Integer intUserid, @Param("intRoleid") Integer intRoleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userrole
     *
     * @mbggenerated
     */
    int insert(SmUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userrole
     *
     * @mbggenerated
     */
    int insertSelective(SmUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userrole
     *
     * @mbggenerated
     */
    SmUserrole selectByPrimaryKey(@Param("intUserid") Integer intUserid, @Param("intRoleid") Integer intRoleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmUserrole record);
}